[package]
name = "microseh"
version = "0.1.0"
authors = ["sonodima"]
edition = "2021"

description = "Structured Exception Handling (SEH) for Rust"
readme = "README.md"
homepage = "https://github.com/sonodima/microseh"
repository = "https://github.com/sonodima/microseh"
license = "MIT"

keywords = ["seh", "windows", "exception", "handler"]
categories = ["os"]


[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["aarch64-pc-windows-msvc", "i686-pc-windows-msvc", "x86_64-pc-windows-msvc"]


[dependencies]
libc = "0.2"
windows-sys = { version = "0.42", features = ["Win32_Foundation"] }

[build-dependencies]
cc = "1.0"
