[package]
name = "microseh"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
windows-sys = { version = "0.42", features = [
    "Win32_Foundation",
    "Win32_System_Kernel",
    "Win32_System_Diagnostics_Debug",
] }

[build-dependencies]
cc = "1.0"
